### ISSUE TITLE
在 prebuilts 目录下放置磁盘文件 `disk.img` 和 bootloader 文件 `rustsbi-qemu.bin`

### ISSUE THREAD

**Issue by phial3** [Dr-TSNG/MinotaurOS#13]
这两文件可以发一下吗

**Comment by Dr-TSNG** [comment]
https://github.com/oscomp/testsuits-for-oskernel/releases/download/2024-final-rv/sdcard-riscv.img.gz
https://github.com/rustsbi/rustsbi-qemu 需要自己构建
